### ISSUE TITLE
API get_client_products 返回的 是空

### ISSUE THREAD

**Issue by LarryZhou021** [Zzm317/Unlimited-Socks#10]
当我尝试执行 php -q /home/wwwroot/Crons/APIbandreset.php 发现
Cann't Access to API(GetClientsProducts)，
但是我稍微修改了一下脚本 echo出get_client_products() ，发现当我错误配置 管理员密码的时候，会返回Access错误，但是当我正确配置管理员密码的时候 返回的结果 是空。
是我什么地方设置错误了吗？
不好意思麻烦了

**Comment by LarryZhou021** [comment]
我后台可以启动API访问日志，可以看到管理员账户通过API的访问记录

**Comment by LarryZhou021** [comment]
我  将 'clientid' => '10' 修改为10 以后，可以查询到用户产品数据

**Comment by LarryZhou021** [comment]
update 我用post调试工具postman调试后发现，返回500错误
我现在打算暂时放弃尝试API，准备重写直接去sql查询whmcs数据库中的hosting表

**Comment by zzm317** [comment]
抱歉 忘記把api上傳了
請先去admin-panel那個項目裡面下載api文件上傳
我一會上傳進去

**Comment by zzm317** [comment]
不對 我看了下
返回空是因為那個api是7.0新增的

**Comment by zzm317** [comment]
請升級版本
舊版本的api需要單獨編寫
如果方便提供環境的話可以聯繫我

**Comment by zzm317** [comment]
还有 这个脚本是根据续费的日来清空流量的，不一定每次都会有输出。

**Comment by LarryZhou021** [comment]
非常感谢你的回复，我有通过Mysql语句查询
 `    $sql = "SELECT
    `orderid`
FROM
    `tblhosting`
WHERE
    `server` = ".SS_SERVER_ID." AND `domainstatus` = 'Active' 
    AND `nextduedate` > CURRENT_DATE 
    AND `regdate` <> DATE_FORMAT(CURRENT_DATE(), '%d ') 
    AND DATE_FORMAT(`regdate`, '%d ') = DATE_FORMAT(CURRENT_DATE(), '%d ')";
`
whmcs 的tblhosting数据库，可以拿到 产品注册日的用户oderid。
不过我突然想到一件事，哈哈可能这查询语句还要完善一下， 因为 每个月不一定都有 31号哈哈哈

**Comment by LarryZhou021** [comment]
因为我仔细观察了 tblhosting表中的 oderid 和 ss 数据库user表的 sid是对应的，目前通过 Mysql 语句直接查询业实现了 api所得到的效果。

 我可能觉得是我 whmcs环境存在问题，有些用户的产品数据我可以取到。

**Comment by zzm317** [comment]
实际上的话不建议直接对whmcs的数据库操作

**Comment by LarryZhou021** [comment]
是啊，我感觉会很危险，所以我单独起了一个只读权限的 账户，做这一操作。但是sql密码还是明文暴露的。
我后面会尝试includes/api/getclientsproducts.php 试试。
我的这个情况实在少见，我觉得可能跟我 之前有删改过 whmcs数据库有关系。

**Comment by zzm317** [comment]
还有。。tblhosting的id和ss的sid对应 而不是orderid。。。。

**Comment by LarryZhou021** [comment]
是啊，最关键，它们不对应....

**Comment by LarryZhou021** [comment]
反而orderid对应...

**Comment by LarryZhou021** [comment]
我之前使用的是https://github.com/kesuki/whmcs-shadowsocks-plugin ，我从它上 直接覆盖升级到你的分支的。

**Comment by zzm317** [comment]
sid部分没有进行过任何修改 与前插件兼容

**Comment by LarryZhou021** [comment]
十分不好意思啊，是我弄错了...
我看到了，确实是 id和 sid对应...

**Comment by zzm317** [comment]
tblhosting的id是和ss的sid对应 如果不对应整个插件会出现bug

**Comment by zzm317** [comment]
可以尝试删除APIBandReset.php的 'clientid' => $id, 然后再测试一下

**Comment by LarryZhou021** [comment]
我尝试过...是这样的..我仔细检查了...只要查询 有开通产品的 clientid ，服务器就会返回500错误...

**Comment by LarryZhou021** [comment]
我的环境是 whmcs 6.3.1

**Comment by LarryZhou021** [comment]
但是我觉得 whmcs 6 的api get_client_products是和现在一样的，所以我目前感觉...很可能是我环境的问题...玄学错误...

**Comment by zzm317** [comment]
whmcs的api可能会有奇怪的问题

**Comment by zzm317** [comment]
测试环境7.2.3 建议升级

**Comment by LarryZhou021** [comment]
好的，后续升级后，我会给予情况的update。
非常感谢耐心回复。麻烦啦~！

**Comment by Zzm317** [comment]
如果有后续update再开启本issue  我先关掉了
