### ISSUE TITLE
请教下最新的流量包功能如何使用？

### ISSUE THREAD

**Issue by infinityhacks** [Zzm317/Unlimited-Socks#13]
请教下最新的流量包功能如何使用？

**Comment by Zzm317** [comment]
导入mysql的card.sql
安装addon里面的插件并且配置好
在插件的cardconfig.php里面配置好流量包的数据库信息（和addon的一样）然后把enable改成true
然后生成流量包卡（在后台给自己插件控制权限以后能找到入口的）
然后使用
