### ISSUE TITLE
Module Settings 无法显示

### ISSUE THREAD

**Issue by liuminghao233** [Zzm317/Unlimited-Socks#14]
fix 一下
![image](https://user-images.githubusercontent.com/13027589/29866687-b84a4068-8dab-11e7-81db-6b8884a19d7a.png)

**Comment by Zzm317** [comment]
切換到其他的再切換回來即可

**Comment by liuminghao233** [comment]
@Zzm317 没有用

**Comment by liuminghao233** [comment]
![image](https://user-images.githubusercontent.com/13027589/29868452-88189600-8db1-11e7-9af5-cb2dd824620c.png)

**Comment by Zzm317** [comment]
換原版後台主題試試

**Comment by liuminghao233** [comment]
@Zzm317 一直是原版呀

**Comment by Zzm317** [comment]
其他的module可以正常刷新？

**Comment by liuminghao233** [comment]
其他的可以

**Comment by liuminghao233** [comment]
@Zzm317 另外release 版V1.0 Beta 2正常

**Comment by Zzm317** [comment]
我這邊問題沒有出現 你確定是覆蓋更新插件的麼

**Comment by liuminghao233** [comment]
whmcs 7.2.3

覆盖更新也是一样

**Comment by Zzm317** [comment]
測試環境whmcs7.2.3 主題blend 問題沒有復現
方便的話發送後台到admin@loli.ren我看下

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/commit/5261595fe16219777805f7e5df26c896afd91af1

已发现出现bug原因 已修正
