### ISSUE TITLE
前台所有的项目后面都跟着一个Missing Language

### ISSUE THREAD

**Issue by logtee** [Zzm317/Unlimited-Socks#15]
我看了下lang目录下的语言包是完好的,这可能是什么问题造成的呢?

**Comment by logtee** [comment]
清cookie之后正常了

**Comment by Zzm317** [comment]
在whmcs的後台清除模板緩存即可

**Comment by Zzm317** [comment]
其他選項-》系統相關-〉系統清理-》清空模板緩存

**Comment by logtee** [comment]
可是这种情况频繁出现怎么破呀?已经清空缓存了,还是出现

**Comment by logtee** [comment]
发现是在模块设置里面提交之后就会出现这个问题,然后pingtest 如果使用test_user模式就会出现这样的错误,如图所示
https://ws1.sinaimg.cn/large/6066e886ly1fj5kcqxug6j20en07cdg3.jpg
这个怎么解决呢?

**Comment by Zzm317** [comment]
pingtest的usertest需要ss服务器上有http的服务器开着 建议使用serverping

**Comment by Zzm317** [comment]
missing language没有出现过 开发环境whmcs7.2.3 php7.0

**Comment by Zzm317** [comment]
前台missinglanguage也有可能是用户的语言默认没设置的原因 你把用户语言调成chinese试试

**Comment by Zzm317** [comment]
后台有出现missinglanguage么？

**Comment by Zzm317** [comment]
看了下你的项目里面有个whmcs汉化项目 你whmcs下来的lang用的是不是chinese-cn.php？

**Comment by Zzm317** [comment]
我知道了=-= 因为你用的语言文件叫chinese-cn.php 插件只有chinese.php 虽然都是中文 但是名字不一样 所以出现missinglanguage 把lang里面的chinese-cn.php改chinese.php就好

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/commit/6e4f45c50dccd606471b35db8a60ece1e7a6bca8
新的commit已修正出现该问题的可能性

**Comment by logtee** [comment]
非常感谢,后台的语言包的名字确实是chinese-cn.php,我发现这个插件前台的语言设置跟随的是whmcs 后台的语言设置 而不是whmcs前台的,是这样吗?因为我字啊后台设置英文显示之后无论在前台怎么更改语言都是显示英文.

**Comment by Zzm317** [comment]
不是 
是当管理员在线的时候跟随管理员语言 用户在线时跟随用户语言

**Comment by Zzm317** [comment]
所有的都不存在时使用默认的

**Comment by logtee** [comment]
明白了,非常感谢!
