### ISSUE TITLE
不知道有没有增加订阅功能的计划？

### ISSUE THREAD

**Issue by sunnus163** [Zzm317/Unlimited-Socks#16]
基本上只能一个节点的慢慢添加，如果能够添加订阅的功能的话，那么还是很方便的

**Comment by Zzm317** [comment]
ss没有订阅功能 因此暂无类似计划

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/commit/3bce78fabaa06273f174a59b4131c5e90503cf3e
