### ISSUE TITLE
无法载入模块和lib/functions.php问题

### ISSUE THREAD

**Issue by samhuang1994** [Zzm317/Unlimited-Socks#17]
直接clone代码UnlimitedSocks.php和hooks.php里不注释掉multi_language_support();无法正常打开服务器设置，显示mysql_real_escape_string($_SESSION[$field])));
if($data = mysql_fetch_row($sqlresult)){
return reset($data);
}
return false;
}

function get_lang($var){
global $_LANG;
return isset($_LANG[$var]) ? $_LANG[$var] : $var . '(Missing Language)' ;

但是注释掉之后产品无法载入模块
2.0版本一样无法载入模块 
whmsc7.2.3版本

**Comment by Zzm317** [comment]
请提供具体的报错 或者直接发错误截图

**Comment by Zzm317** [comment]
试一下 https://github.com/Zzm317/Unlimited-Socks/commit/47cc406ab65a6048af9a203ffc8d66e29cd83bb3

**Comment by samhuang1994** [comment]
@Zzm317 问题依旧，怀疑php版本问题 更换php7一样不行 
没有注释报错 [https://i.imgur.com/T4Exjqk.png](url)
注释后模块设置加载不出来 [https://i.imgur.com/wyJrmHu.png](url)

**Comment by Zzm317** [comment]
。。。你就给我截个oops有什么用啊
我要下面的报错详情啊
测试环境php7 whmcs7.2.3 没有复现问题
还有 1.0beta2 也有multi_language_support这个函数啊

**Comment by samhuang1994** [comment]
原来是7.0.1的版本进服务器设置直接显示mysql_real_escape_string($_SESSION[$field])));这段往后的代码 但是升级到7.2.3就直接剩个oops了 没有报错详情 
1.0和2.0 multi_language_support()这个函数没有单独分文件写是没问题的 
强制套用chinese.php可以解决问题 
不过2.0版本往后在产品设置里无法载入模块

**Comment by Zzm317** [comment]
请确认你在设置中开启了错误显示
我实在是没看懂你的意思
如果可以请联系我qq 1013452574 或者 telegram @nagakasuzume 提供更多详细信息
