### ISSUE TITLE
二维码无法识别

### ISSUE THREAD

**Issue by logtee** [Zzm317/Unlimited-Socks#18]
发现安卓版和windows版的识别无问题,并且还能显示服务器别名,ios上shadowrocket名字会乱码
mac上shadowsocksX-NG无法识别二维码

**Comment by Zzm317** [comment]
shadowrocket问题 就算是电脑端生成的也无法正常识别中文 应该是编写的人漏写了urldecode 建议找开发者解决
还有请不要使用如此笼统的标题提issue好么 看着吓人

**Comment by Zzm317** [comment]
还有就是实际上是不建议使用中文做备注的 容易炸 ssr的没问题是因为ssr的remark是base64_encode的，ss的是直接在后面加#的=-=

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/commit/921d4c4dfe682391b799642f77824c05aa6b0d35

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/commit/1c996d76ff3e95479b1c1f348f26901a39384a38
用这个把 加了个ss的区分=-= IOS,mac 和 android,win

**Comment by logtee** [comment]
更新了下,默认效果就和你说的一样,反过来了,然而并没有区分,看了下代码.
请问 {if is_array($node[8])}这里是判断的什么?

**Comment by logtee** [comment]
幸苦了，那我等更新了。

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/commit/df41515b0883b88fc80be0d36c5da61a73530403

**Comment by logtee** [comment]
点击查看URL 弹出来这样
http://ww1.sinaimg.cn/large/6066e886ly1fjol60az2oj207v04j0so.jpg

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/commit/fe16ac21785319dd424031e3896b95719909da60

**Comment by Zzm317** [comment]
请问 {if is_array($node[8])}这里是判断的什么?
之前ss&ssr模式的node8是一个数组 非数组的情况下 node8就是ss或者ssr的连接 判断是数组就能知道是不是兼容模式 然后显示对应内容
现在改成判断node7的模式了

**Comment by Zzm317** [comment]
之前用百度的api的时候直接不识别#后面的备注 所以更换成用js显示的

**Comment by logtee** [comment]
还是前面提到的问题,wingy和shadowsocksX-NG,还有最新版的shadowsocks for windows 4.0.6都无法识别生成的二维码,这是什么原因早成的呢?

**Comment by Zzm317** [comment]
两个二维码都不行还是什么

**Comment by Zzm317** [comment]
ss for win那个可能是二维码识别出了问题 都扫不出来 但是url可以

**Comment by logtee** [comment]
实测是两个二维码都提示无法解析

**Comment by Zzm317** [comment]
urlne

**Comment by Zzm317** [comment]
url呢

**Comment by logtee** [comment]
从剪贴板导入url这选项我是第一次才发现,依然是没有反应,shadowrocket和安卓版的都能识别.

**Comment by Zzm317** [comment]
手动添加 然后复制出url发给我

**Comment by logtee** [comment]
我在telegram上发你吧~

**Comment by Zzm317** [comment]
https://github.com/shadowsocks/shadowsocks-windows/issues/1374
4.0.6的bug 暂未修复 与插件无关

**Comment by Zzm317** [comment]
emmmmm拿了男票票的mac看了下
ssx的二维码简直神奇
wingy应该也是一个情况

**Comment by logtee** [comment]
难道你是妹子？汗！

**Comment by Zzm317** [comment]
ssx的二维码有两种模式 要么只b64加密方式和密码 要么全部加密 服气的

**Comment by Zzm317** [comment]
我一会推个更新你测测wingy吧

**Comment by Zzm317** [comment]
推了 你试试吧
