### ISSUE TITLE
关于续费流量重置和中文乱码的问题

### ISSUE THREAD

**Issue by Kogami233** [zzm317/Unlimited-Socks#2]
你好~=￣ω￣=
看了你的重置文件，我有一个疑问，年费用户是否会也会在每个月的购买日重置流量
还有关于扫入二维码中文乱码的问题
因为你刚刚更新插件我就用上了，那个时候出现ping检测按钮不正确，我在前端给注释掉了
是否替换js文件就行，不用替换其他的文件
感谢你每次都能及时的回复_(:з」∠)_

**Comment by zzm317** [comment]
具体看commit乱码修改了哪些文件
关于重置 年费也会每个月重置的

**Comment by zzm317** [comment]
需要检测的话我后面改

**Comment by zzm317** [comment]
要改就提issue

**Comment by Kogami233** [comment]
不需要检测了   我自己试着替换吧
感谢(●'◡'●)ﾉ

**Comment by zzm317** [comment]
建议是直接全部更新，现在新的是可以选择不检测ping的（产品设置里面

**Comment by Kogami233** [comment]
好的  我试试

**Comment by zzm317** [comment]
没问题的话我先close这个issue了
