### ISSUE TITLE
大佬有计划支持单端口多用户and中转么

### ISSUE THREAD

**Issue by echoowall** [Zzm317/Unlimited-Socks#22]
大佬有计划支持单端口多用户and中转么

**Comment by Zzm317** [comment]
单端口多用户？中转？
能具体解释一下么

**Comment by YinHangCode** [comment]
![qq 20171127195555](https://user-images.githubusercontent.com/15974677/33265686-91b18356-d3ad-11e7-983f-33ed24f49dc9.jpg)

**Comment by hinext** [comment]
单端口多用户的话，就是可以设定某个端口可以承载全站用户的访问。
可以看一下

V3魔改https://github.com/esdeathlove/ss-panel-v3-mod

SSR panel:  https://github.com/ssrpanel/SSRPanel
