### ISSUE TITLE
请问可否支持每个用户单独加密/协议/混淆配置 

### ISSUE THREAD

**Issue by lelemka0** [Zzm317/Unlimited-Socks#24]
请问可否支持每个用户单独加密/协议/混淆配置，SSR后端支持此功能(需将userapiconfig.py:API_INTERFACE设为sspanelv3ssr)。
数据库部分参见ss-pancl-v3/v4, https://github.com/orvice/ss-panel/tree/dev
希望大佬有空可以看下，谢谢。

**Comment by Zzm317** [comment]
可以 但是这样做意味着要修改数据库了
可能需要下一个大版本才会加

**Comment by Zzm317** [comment]
还有 你得给我一个正常的带sspanel v3的后端

**Comment by Zzm317** [comment]
仔细想了一下 如果做单独的 相当于整套数据库 配置系统全部要重写
作为一个个人开发者 这个工程量可能实在是有点大

**Comment by hinext** [comment]
后端的话，这个好像可以的
https://github.com/shadowsocksr-backup/shadowsocksr/tree/manyuser

能否通过whmcs的升降级修改掉数据库的加密混淆之类的信息？

除此之外，订阅功能貌似很有用（前提是用ssr）,如果可以的话，麻烦大佬有空的时候，添加一下。

最后，谢谢大佬维护插件

**Comment by Zzm317** [comment]
订阅不可能加的 除非哪天我去做公益ss 不再需要考虑账号滥用的问题

https://github.com/kesuki/whmcs-shadowsocks-plugin/issues/29

**Comment by Zzm317** [comment]
至于自定义加密混淆 可能会单独做分支 如果实在想用 建议直接上全解legendsocks吧 我这套插件设计的时候就没考虑做自定义混淆和加密 所以要做的话会需要很长时间
如果需要全解的可以给我发邮件我发给你

**Comment by lelemka0** [comment]
https://github.com/shadowsocksr-backup/shadowsocksr/tree/manyuser
这个后端可以支持sspanelv3ssr
将userapiconfig.py中API_INTERFACE设为sspanelv3ssr

**Comment by Zzm317** [comment]
主要是设计的时候就没有设计自定义加密混淆 只做了自定义密码
