### ISSUE TITLE
混淆参数错位

### ISSUE THREAD

**Issue by herpherd** [Zzm317/Unlimited-Socks#25]
自上一次更新之后一直很好用,但是最近发现讲混淆参数加入之后扫描二维码参数会错位.
格式是:US1 |s1.test.com|rc4-md5|auth_aes128_md5||tls1.2_ticket_auth|cloudflare.com,www.baidu.com,www.taobao.com|ssr
生成的二维码是:https://ws1.sinaimg.cn/large/6066e886gy1fnp5oxjybhj206p06pwef
用shadowrocket扫描之后,混淆参数出现在了协议参数的位置.
如图所示:https://ws1.sinaimg.cn/large/6066e886gy1fnp5tebjpbj20hs0vk3zt
安卓客户端也是相同的问题:https://ws1.sinaimg.cn/large/6066e886gy1fnp6828pfqj20u01hcdhb
不知是什么问题?

**Comment by Zzm317** [comment]
我看看

**Comment by Zzm317** [comment]
真的非常抱歉！我写反了！

**Comment by Zzm317** [comment]
已经推送更新修复了 真的十分抱歉！

**Comment by logtee** [comment]
感谢~
