### ISSUE TITLE
如果大佬还继续开发的话，提个建议

### ISSUE THREAD

**Issue by hinext** [Zzm317/Unlimited-Socks#26]
可以参考一下legendsocks

https://babytomas.gitbooks.io/legendsock-for-whmcs-docs/

估计可以提供一下思路。

**Comment by Zzm317** [comment]
legendsocks全解修复我有

**Comment by hinext** [comment]
恩恩

**Comment by zhkufish** [comment]
legendsocks全解修复 可以发给我研究一下么?

**Comment by Zzm317** [comment]
那我想要100w 可以发给我么？
