### ISSUE TITLE
大佬 订阅连接无效怎么解决啊

### ISSUE THREAD

**Issue by YGdevi** [Zzm317/Unlimited-Socks#28]
如题，是不是如果要用订阅，ssr后端要换api接口啊，用哪个接口可以使用，我安装完配置好，订阅连接放入浏览器打开，出现“Invaild”，不知道错在那个地方了，求指教

**Comment by Zzm317** [comment]
出现Invaild的情况只有链接有误的情况
也就是没有包含sid和token
请检查链接

**Comment by YGdevi** [comment]
重新装了下 插件不能使用了。。怎么解决啊。。
![chrome_2018-02-21_15-28-47](https://user-images.githubusercontent.com/21022713/36467938-20f09e24-171c-11e8-87d5-09c699001340.png)

**Comment by YGdevi** [comment]
网站网址/modules/servers/UnlimitedSocks/subscribe.php?sid=11&token=%Vtu9ZrGUAGU 订阅连接是这样的格式对吧？ 装了好多次 最后再次在浏览器打开 显示的是“cwo=”这几个字母，连接依然没办法使用，求指导！！谢谢

**Comment by Zzm317** [comment]
你线路填了么 没有线路的话不会有输出的

**Comment by YGdevi** [comment]
线路已经填写了  


![chrome_2018-02-22_13-32-09](https://user-images.githubusercontent.com/21022713/36522127-b3430690-17d5-11e8-9290-dae8affb9ec0.png)
难道是我后端用错了？

**Comment by Zzm317** [comment]
和后端没有关系的
这样 你在https://github.com/Zzm317/Unlimited-Socks/blob/master/Plugin/UnlimitedSocks/subscribe.php 的第38行加一句 var_dump($servers);
看一下有没有正常获取到线路

**Comment by YGdevi** [comment]
![chrome_2018-02-24_11-57-50](https://user-images.githubusercontent.com/21022713/36625411-0ed65e8c-195a-11e8-8609-aa824e20f2c6.png)
加上后 用网页打开是这样的  用客户端依然没办法订阅 弄了好久 不知道错哪了0.0.。

**Comment by Zzm317** [comment]
你随便加一条线路试试

**Comment by Zzm317** [comment]
我让你var_dump只是我看着调试用的 和订阅正常不正常有什么关系

**Comment by YGdevi** [comment]
变成这样了
![chrome_2018-02-24_12-12-04](https://user-images.githubusercontent.com/21022713/36625529-25e7e03a-195c-11e8-8904-6fda86524a78.png)

**Comment by Zzm317** [comment]
你把var_dump($results); 然后看一下输出什么

**Comment by YGdevi** [comment]
![chrome_2018-02-24_13-37-55](https://user-images.githubusercontent.com/21022713/36626142-0dd21702-1968-11e8-942c-50fa6afaff5b.png)
是这样的嗯

**Comment by Zzm317** [comment]
那你把之前加的都去掉 然后在echo(base64_encode($finalresult));前面加一句var_dump($finalresult); 看一下输出什么

**Comment by YGdevi** [comment]
![chrome_2018-02-24_21-31-54](https://user-images.githubusercontent.com/21022713/36630942-30c96174-19aa-11e8-9613-6930d109da83.png)
只显示这个

**Comment by Zzm317** [comment]
修正了 你更新试一下

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/blob/master/Plugin/UnlimitedSocks/subscribe.php

**Comment by YGdevi** [comment]
![chrome_2018-02-26_12-02-49](https://user-images.githubusercontent.com/21022713/36652964-118dc7d4-1aed-11e8-980b-614d68348fad.png)
依然没办法订阅 我直接导入的链接地址好像和这上面显示出来的链接不一样

**Comment by requestdeny** [comment]
我的订阅链接是能显示。解base64以后发现没有获取到端口。少了端口那一行。导致了订阅没法自动更新。是哪里没设置对么

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/blob/master/Plugin/UnlimitedSocks/subscribe.php
修复了bug了 win上和梅林上测试没问题

**Comment by Zzm317** [comment]
Mac ssx-ng测试通过
