### ISSUE TITLE
怎么通过Linux命令暂停端口啊？

### ISSUE THREAD

**Issue by Kogami233** [zzm317/Unlimited-Socks#3]
前端一个个找太麻烦了
求教

**Comment by Kogami233** [comment]
老大，全部替换后，二维码和连接用不了了

**Comment by zzm317** [comment]
你确定全部替换了？有没有用cdn？有没有刷新cdn缓存？

**Comment by Kogami233** [comment]
我替换了这个文件夹UnlimitedSocks，没有用cdn，我的数据库是上个作者的那个。相比你一开始的同一个文件，我看了下你按钮里好像没写东西。

**Comment by zzm317** [comment]
检查按钮部分是不是<button name="url" class="btn btn-primary btn-xs" data-params=“”>

**Comment by zzm317** [comment]
检查js里面是不是$("button[name='url']").on('click',function() {
			str = $(this).attr('data-params');
			layer.alert(str);
		});

**Comment by Kogami233** [comment]
是的，但是你按钮里面好像没有调用js

**Comment by zzm317** [comment]
你清除一下瀏覽器的cache試試

**Comment by zzm317** [comment]
關於調用問題
js裡面有$(document).ready(function() {
