### ISSUE TITLE
想问下节点要怎么配置

### ISSUE THREAD

**Issue by ZJY2003** [Zzm317/Unlimited-Socks#30]
节点已经设置对接了数据库，但是提示找不到数据表。要怎样建立数据表呢

**Comment by Zzm317** [comment]
https://github.com/Zzm317/Unlimited-Socks/blob/master/Sql/Readme.md

**Comment by ZJY2003** [comment]
节点已经搭建好了，但是现在有一个问题就是windows下好像订阅有点小问题。IOS的shadowrocket通过了。

**Comment by Zzm317** [comment]
win上和梅林上测试没问题
Mac上测试通过

**Comment by ZJY2003** [comment]
把sspanel的订阅地址输入浏览器会自动下载一个txt文件，而用您这个插件打开以后直接是plain text

**Comment by ZJY2003** [comment]
可能是我用了ssrr客户端，我测试一下ssr客户端

**Comment by ZJY2003** [comment]
windows下还是没有反应。方便发一下你的ssr客户端吗

**Comment by Zzm317** [comment]
测试版本是 Windows系统 - ShadowsocksR 4.7.0
我只保证大部分版本能用
毕竟我本身是不想添加这个功能的

**Comment by ZJY2003** [comment]
好的谢谢。
