### ISSUE TITLE
admin-panel现在能用吗？管理的帐号密码是什么？

### ISSUE THREAD

**Issue by infinityhacks** [zzm317/Unlimited-Socks#4]

**Comment by zzm317** [comment]
目前没有完成全部编写
管理员账号密码和你whmcs后台的密码一样
具体参照readme.md

**Comment by infinityhacks** [comment]
我用admin帐号试了试，登录不了，也不提示任何错误信息

**Comment by zzm317** [comment]
1.Edit config/config.php to your site(If You use CDN you can only upload the panel to the server and use 127.0.0.1)|
1.修改config/config.php(如果你使用cdn，那么你只能上传panel到服务器上并使用127.0.0.1了)
2.Add API IP in System->General->security|在System->General->security中添加访问API的ip

**Comment by zzm317** [comment]
这三步照做了么

**Comment by 755048652** [comment]
@zzm317 相同的问题，还以为是没编写完成的原因，请问那个panel是上传到那个文件夹。。。

**Comment by zzm317** [comment]
上传到哪里问题不大
主要是必须在系统设置里面的安全里面加上panel的ip
如果是上传到同一个目录就127.0.0.1就ok

**Comment by zzm317** [comment]
https://github.com/zzm317/Unlimited-Socks/commit/fc7c27ae8ad47c27699dee30d5b0d4ccca82e3cb
可以下载这个commit看一下返回的错误是什么

**Comment by zzm317** [comment]
还有这个
https://github.com/zzm317/Unlimited-Socks/commit/f90f2cd5a175e00c088b1fd220658685613b81e7

**Comment by 755048652** [comment]
@zzm317 能不能出个教程大神，还是一样的点登陆没反应

**Comment by zzm317** [comment]
那等我写完再说把
前期你们自己折腾下先
主要就是这两个步骤啊
1.修改config/config.php(如果你使用cdn，那么你只能上传panel到服务器上并使用127.0.0.1了)
2.在System->General->security中添加访问API的ip

比如我把panel放在admin目录下面
config里面我写的就是127.0.0.1/includes/api.php
在System->General->security中添加的就是127.0.0.1

**Comment by zzm317** [comment]
adminpanel已移动至 https://github.com/zzm317/Unlimited-Socks-AdminPanel 并与UnlimitedSocks同步开发
issue请移步至那边
