### ISSUE TITLE
测试了下ss的二维码,发现无法识别

### ISSUE THREAD

**Issue by logtee** [zzm317/Unlimited-Socks#5]
生成的图片的url:http://pan.baidu.com/share/qrcode?w=300&h=300&url=://cmM0LW1kNToxMjM0NTZAMS4yLjMuNDoxMDAwMA==

我发现://前面少了一个ss,导致生成的二维码无法识别,能修复一下吗?谢谢啦~
然后添加了ssr格式的服务器,在://前面也缺少了一个ssr,这样说生成出来的二维码都无法识别呢

**Comment by zzm317** [comment]
能不能去產品/服務裡面
看一下線路列表裡面的備註
在好幾個commit之前就已經更新了線路列表的格式了

**Comment by zzm317** [comment]
格式 xxx|服务器地址|加密方式|协议|协议参数|混淆|混淆参数|ss/ssr 一行一个

**Comment by logtee** [comment]
非常感谢指点
