### ISSUE TITLE
您好，SSR 4.5以上版本扫找二维码无法识别。

### ISSUE THREAD

**Issue by 3214391275** [zzm317/Unlimited-Socks#7]
zzm317 
已修正
请下载最新的版本替换使用

————————————————————————————————————————

您好，替换后，二维码和URL按钮点击都不弹出了。

**Comment by zzm317** [comment]
沒有對js文件進行修改
請檢查是否有跨多版本更新
如果有 請清除whmcs的頁面文件緩存 並且刷新cdn緩存
