### ISSUE TITLE
结账页面会卡住，然后显示503

### ISSUE THREAD

**Issue by 511981293** [zzm317/Unlimited-Socks#9]
如题，求大佬解答

**Comment by zzm317** [comment]
请提供更加详细的说明

**Comment by 511981293** [comment]
![tim 20170810125726](https://user-images.githubusercontent.com/30888258/29155041-b9a053a2-7dcb-11e7-9230-13d1c7ae00f8.png)
![tim 20170810125935](https://user-images.githubusercontent.com/30888258/29155050-c87d05f0-7dcb-11e7-96b8-ae90b7ce7f8a.png)
已经按照说明配置完成了以后，测试数据库连接什么的都正常，但是在前台使用账号登录并测试购买的时候，点击结账按钮后会一直卡住，这个时候后台也没法进，过段时间会出现503的报错

**Comment by zzm317** [comment]
提供的信息太少 无法判断问题所在
请email我提供后台账号或rdp权限

**Comment by 511981293** [comment]
已发邮件，多谢大佬
